# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from boltz_service.protos import common_pb2 as common__pb2
from boltz_service.protos import msa_service_pb2 as msa__service__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in msa_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MSAServiceStub(object):
    """MSA generation service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateMSA = channel.unary_unary(
                '/boltz.MSAService/GenerateMSA',
                request_serializer=msa__service__pb2.MSARequest.SerializeToString,
                response_deserializer=msa__service__pb2.MSAResponse.FromString,
                _registered_method=True)
        self.GetJobStatus = channel.unary_unary(
                '/boltz.MSAService/GetJobStatus',
                request_serializer=common__pb2.JobStatusRequest.SerializeToString,
                response_deserializer=common__pb2.JobStatusResponse.FromString,
                _registered_method=True)
        self.CancelJob = channel.unary_unary(
                '/boltz.MSAService/CancelJob',
                request_serializer=common__pb2.CancelJobRequest.SerializeToString,
                response_deserializer=common__pb2.CancelJobResponse.FromString,
                _registered_method=True)


class MSAServiceServicer(object):
    """MSA generation service
    """

    def GenerateMSA(self, request, context):
        """Generate MSA for a sequence
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobStatus(self, request, context):
        """Get MSA job status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelJob(self, request, context):
        """Cancel MSA job
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MSAServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateMSA': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateMSA,
                    request_deserializer=msa__service__pb2.MSARequest.FromString,
                    response_serializer=msa__service__pb2.MSAResponse.SerializeToString,
            ),
            'GetJobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobStatus,
                    request_deserializer=common__pb2.JobStatusRequest.FromString,
                    response_serializer=common__pb2.JobStatusResponse.SerializeToString,
            ),
            'CancelJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelJob,
                    request_deserializer=common__pb2.CancelJobRequest.FromString,
                    response_serializer=common__pb2.CancelJobResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'boltz.MSAService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('boltz.MSAService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MSAService(object):
    """MSA generation service
    """

    @staticmethod
    def GenerateMSA(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boltz.MSAService/GenerateMSA',
            msa__service__pb2.MSARequest.SerializeToString,
            msa__service__pb2.MSAResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boltz.MSAService/GetJobStatus',
            common__pb2.JobStatusRequest.SerializeToString,
            common__pb2.JobStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boltz.MSAService/CancelJob',
            common__pb2.CancelJobRequest.SerializeToString,
            common__pb2.CancelJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
