apiVersion: apps/v1
kind: Deployment
metadata:
  name: boltz-service
  namespace: default
  labels:
    app: boltz
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boltz
  template:
    metadata:
      labels:
        app: boltz
    spec:
      containers:
      - name: boltz-container
        image: boltz-service:latest
        ports:
        - containerPort: 50051
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1
            memory: 2Gi
        env:
        - name: GRPC_VERBOSITY
          value: "debug"
        - name: BOLTZ_MODEL_PATH
          value: "/models/boltz_model.pt"
        volumeMounts:
        - name: model-storage
          mountPath: /models
      volumes:
      - name: model-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: boltz-service
  namespace: default
spec:
  selector:
    app: boltz
  ports:
  - port: 50051
    targetPort: 50051
  type: ClusterIP
