apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-config
data:
  AWS_REGION: "${AWS_REGION}"
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
  AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
