# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from boltz_service.protos import common_pb2 as common__pb2
from boltz_service.protos import inference_service_pb2 as inference__service__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in inference_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InferenceServiceStub(object):
    """Inference service for protein structure prediction
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PredictStructure = channel.unary_unary(
                '/boltz.InferenceService/PredictStructure',
                request_serializer=inference__service__pb2.PredictionRequest.SerializeToString,
                response_deserializer=inference__service__pb2.PredictionResponse.FromString,
                _registered_method=True)
        self.GetJobStatus = channel.unary_unary(
                '/boltz.InferenceService/GetJobStatus',
                request_serializer=common__pb2.JobStatusRequest.SerializeToString,
                response_deserializer=common__pb2.JobStatusResponse.FromString,
                _registered_method=True)
        self.CancelJob = channel.unary_unary(
                '/boltz.InferenceService/CancelJob',
                request_serializer=common__pb2.CancelJobRequest.SerializeToString,
                response_deserializer=common__pb2.CancelJobResponse.FromString,
                _registered_method=True)


class InferenceServiceServicer(object):
    """Inference service for protein structure prediction
    """

    def PredictStructure(self, request, context):
        """Predict protein structure from sequence
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobStatus(self, request, context):
        """Get prediction job status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelJob(self, request, context):
        """Cancel prediction job
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PredictStructure': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictStructure,
                    request_deserializer=inference__service__pb2.PredictionRequest.FromString,
                    response_serializer=inference__service__pb2.PredictionResponse.SerializeToString,
            ),
            'GetJobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobStatus,
                    request_deserializer=common__pb2.JobStatusRequest.FromString,
                    response_serializer=common__pb2.JobStatusResponse.SerializeToString,
            ),
            'CancelJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelJob,
                    request_deserializer=common__pb2.CancelJobRequest.FromString,
                    response_serializer=common__pb2.CancelJobResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'boltz.InferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('boltz.InferenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InferenceService(object):
    """Inference service for protein structure prediction
    """

    @staticmethod
    def PredictStructure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boltz.InferenceService/PredictStructure',
            inference__service__pb2.PredictionRequest.SerializeToString,
            inference__service__pb2.PredictionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boltz.InferenceService/GetJobStatus',
            common__pb2.JobStatusRequest.SerializeToString,
            common__pb2.JobStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boltz.InferenceService/CancelJob',
            common__pb2.CancelJobRequest.SerializeToString,
            common__pb2.CancelJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
