# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: msa_service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'msa_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import boltz_service.protos.common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11msa_service.proto\x12\x05\x62oltz\x1a\x0c\x63ommon.proto\"n\n\nMSARequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x10\n\x08sequence\x18\x02 \x01(\t\x12\x10\n\x08max_seqs\x18\x03 \x01(\x05\x12\x14\n\x0cmin_identity\x18\x04 \x01(\x02\x12\x16\n\x0enum_iterations\x18\x05 \x01(\x05\"Y\n\x0bMSAResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x13\n\x0bresult_path\x18\x03 \x01(\t\x12\x15\n\rerror_message\x18\x04 \x01(\t2\xcb\x01\n\nMSAService\x12\x36\n\x0bGenerateMSA\x12\x11.boltz.MSARequest\x1a\x12.boltz.MSAResponse\"\x00\x12\x43\n\x0cGetJobStatus\x12\x17.boltz.JobStatusRequest\x1a\x18.boltz.JobStatusResponse\"\x00\x12@\n\tCancelJob\x12\x17.boltz.CancelJobRequest\x1a\x18.boltz.CancelJobResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'msa_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MSAREQUEST']._serialized_start=42
  _globals['_MSAREQUEST']._serialized_end=152
  _globals['_MSARESPONSE']._serialized_start=154
  _globals['_MSARESPONSE']._serialized_end=243
  _globals['_MSASERVICE']._serialized_start=246
  _globals['_MSASERVICE']._serialized_end=449
# @@protoc_insertion_point(module_scope)
