# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from boltz_service.protos import common_pb2 as common__pb2
from boltz_service.protos import training_service_pb2 as training__service__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in training_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TrainingServiceStub(object):
    """Training service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartTraining = channel.unary_unary(
                '/boltz.TrainingService/StartTraining',
                request_serializer=training__service__pb2.TrainingRequest.SerializeToString,
                response_deserializer=training__service__pb2.TrainingResponse.FromString,
                _registered_method=True)
        self.GetJobStatus = channel.unary_unary(
                '/boltz.TrainingService/GetJobStatus',
                request_serializer=common__pb2.JobStatusRequest.SerializeToString,
                response_deserializer=training__service__pb2.TrainingJobStatusResponse.FromString,
                _registered_method=True)
        self.CancelJob = channel.unary_unary(
                '/boltz.TrainingService/CancelJob',
                request_serializer=common__pb2.CancelJobRequest.SerializeToString,
                response_deserializer=common__pb2.CancelJobResponse.FromString,
                _registered_method=True)
        self.ExportModel = channel.unary_unary(
                '/boltz.TrainingService/ExportModel',
                request_serializer=training__service__pb2.ExportModelRequest.SerializeToString,
                response_deserializer=training__service__pb2.ExportModelResponse.FromString,
                _registered_method=True)


class TrainingServiceServicer(object):
    """Training service
    """

    def StartTraining(self, request, context):
        """Start training job
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobStatus(self, request, context):
        """Get training job status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelJob(self, request, context):
        """Cancel training job
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportModel(self, request, context):
        """Export model
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrainingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartTraining': grpc.unary_unary_rpc_method_handler(
                    servicer.StartTraining,
                    request_deserializer=training__service__pb2.TrainingRequest.FromString,
                    response_serializer=training__service__pb2.TrainingResponse.SerializeToString,
            ),
            'GetJobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobStatus,
                    request_deserializer=common__pb2.JobStatusRequest.FromString,
                    response_serializer=training__service__pb2.TrainingJobStatusResponse.SerializeToString,
            ),
            'CancelJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelJob,
                    request_deserializer=common__pb2.CancelJobRequest.FromString,
                    response_serializer=common__pb2.CancelJobResponse.SerializeToString,
            ),
            'ExportModel': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportModel,
                    request_deserializer=training__service__pb2.ExportModelRequest.FromString,
                    response_serializer=training__service__pb2.ExportModelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'boltz.TrainingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('boltz.TrainingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TrainingService(object):
    """Training service
    """

    @staticmethod
    def StartTraining(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boltz.TrainingService/StartTraining',
            training__service__pb2.TrainingRequest.SerializeToString,
            training__service__pb2.TrainingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boltz.TrainingService/GetJobStatus',
            common__pb2.JobStatusRequest.SerializeToString,
            training__service__pb2.TrainingJobStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boltz.TrainingService/CancelJob',
            common__pb2.CancelJobRequest.SerializeToString,
            common__pb2.CancelJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/boltz.TrainingService/ExportModel',
            training__service__pb2.ExportModelRequest.SerializeToString,
            training__service__pb2.ExportModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
