apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: boltz-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi  # Adjust size based on your needs
  storageClassName: alicloud-disk-efficiency
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: boltz-cache-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi  # Adjust size based on your needs
  storageClassName: alicloud-disk-efficiency
