---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bfd-data
  namespace: boltz
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cache-data
  namespace: boltz
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard
