name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
        
    - name: Run tests
      run: |
        pytest tests/
        
    - name: Run type checking
      run: |
        mypy src/
        
    - name: Run linting
      run: |
        flake8 src/
        
  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push inference image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: docker/inference.Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/boltz-inference:latest
          ghcr.io/${{ github.repository }}/boltz-inference:${{ github.sha }}
          
    - name: Build and push training image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: docker/training.Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/boltz-training:latest
          ghcr.io/${{ github.repository }}/boltz-training:${{ github.sha }}
